import Head from "next/head";
import { useState } from "react";
import { HelloData } from "./api/hello";

export default function Home() {
	const [response, setResponse] = useState<HelloData>();
	const [count, setCount] = useState<number>(0);

	const requestHello = async () => {
		const helloDate = await (await fetch("/api/hello")).json();
		setCount(count + 1);
		setResponse(helloDate);
	};

	return (
		<div>
			<Head>
				<title>Upstash-ratelimter</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<button onClick={requestHello}>Request</button>
				<p>Resquest count: {count}</p>
				<p>Response: {response?.greetings}</p>
				<p>Error: {response?.error}</p>
			</main>
		</div>
	);
}
